# spring.datasource.url=jdbc:mysql://localhost:3306/quiz?serverTimezone=JST
# spring.datasource.username=root
# spring.datasource.password=password
# spring.datasource.driverClassName=com.mysql.jdbc.Driver
# spring.jpa.database=MYSQL
# spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?serverTimezone=JST
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update